### ISSUE TITLE
Mobile HAR pipeline failing

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/bigquery#32]
```
        [...]
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.httparchive.dataflow.BigQueryImport$DataExtractorFn.processElement(BigQueryImport.java:222)
```

https://github.com/HTTPArchive/bigquery/blob/master/dataflow/java/src/main/java/com/httparchive/dataflow/BigQueryImport.java#L222

This code processes LH results. I think in the latest LH release there were some changes to the JSON LHR, so I'll have to update this.

(PS: Yay for Stackdriver error notifications!)

**Comment by rviscomi** [comment]
Found a HAR that demonstrates the breakage: https://cdn.httparchive.org/android-Mar_15_2018/180324_10_1YMJ.har.gz

The root cause is the `_lighthouse` value is an empty array. Until now we've only expected this to be null or an object. Adding additional checks to ensure that it is an object with expected properties should do the trick.

**Comment by rviscomi** [comment]
Deployed to GCE
